### PR TITLE
Theme

### LINKED ISSUE #10: 暗黑模式
PR welcome

### PR DESCRIPTION
**Pull request by Karlatemp**
_No description provided._

---

close #10

### CODE REVIEW

**Comment by Clansty** [comment]
@Karlatemp 草！强强

**Comment by Karlatemp** [comment]
~~Who is 强强~~

**Review by Clansty — APPROVED** [review]

**Comment by Clansty** [comment]
真好，感谢QwQ

**Comment by rain15z3** [comment]
好耶～强强

**Pull request merged**
